apiVersion: apps/v1
kind: Deployment
metadata:
  name: licznik-stable
  labels:
    app: licznik-canary
    track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: licznik-canary
      track: stable
  template:
    metadata:
      labels:
        app: licznik-canary
        track: stable
        version: "1.0.4"
    spec:
      containers:
        - name: licznik
          image: devops-counter-app:1.0.4
          imagePullPolicy: Never
          ports:
            - containerPort: 3000