apiVersion: apps/v1
kind: Deployment
metadata:
  name: licznik-recreate
  labels:
    app: licznik-recreate
    version: "1.0.4"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: licznik-recreate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: licznik-recreate
        version: "1.0.4"
    spec:
      containers:
        - name: licznik
          image: devops-counter-app:1.0.5
          imagePullPolicy: Never
          ports:
            - containerPort: 3000